<a href="https://colab.research.google.com/github/goygoyummm/2022_CUNY_DS_Bridge_Python/blob/main/Week_2_Question_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#3.  Write a Python program to compute the determinant of an array.
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[9, 8, 2],
[11, 5, 26],
[7, 8, 5]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[ 9  8  2]
 [11  5 26]
 [ 7  8  5]]
-524.9999999999999
