<a href="https://colab.research.google.com/github/goygoyummm/2022_CUNY_DS_Bridge_Python/blob/main/Week_2_Question_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

#Question #2
#2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
#define matrix
A=array([
[8,6],
[4,6],
[2,1]         
])
print(A)
#factorize
U,s,V=svd(A)
print(U)
print(s)
print(V)

[[8 6]
 [4 6]
 [2 1]]
[[-0.80479483  0.504722   -0.31234752]
 [-0.56757772 -0.808372    0.15617376]
 [-0.17366866  0.30296933  0.93704257]]
[12.35735046  2.07265279]
[[-0.73284374 -0.68039699]
 [ 0.68039699 -0.73284374]]
